// Curated interest list. Must stay in sync with supabase/replace-interests.sql —
// labels and categories here must match the rows seeded in the database exactly.
// `label` is the category (group) name; `items` are its individual interests.
export type InterestCategory = {
  label: string;
  items: string[];
};

export const INTEREST_CATEGORIES: InterestCategory[] = [
  {
    label: 'Sports',
    items: [
      'Soccer',
      'Basketball',
      'Tennis',
      'Football',
      'Baseball',
      'Volleyball',
      'Motorsport / F1',
      'Golf',
      'Combat sports (boxing / MMA / BJJ)',
      'Racket sports (squash / badminton / table tennis)',
      'Weightlifting',
      'Running',
    ],
  },
  {
    label: 'Food & Cooking',
    items: [
      'Baking',
      'Italian food',
      'Japanese / sushi',
      'Mexican food',
      'Indian food',
      'Korean food',
      'Coffee & café culture',
      'Cooking',
      'Thai / Southeast Asian',
      'Vegan / vegetarian',
    ],
  },
  {
    label: 'Leisure',
    items: [
      'Reading',
      'Board games',
      'Chess',
      'Poker / card games',
      'Tabletop RPGs (D&D)',
      'Puzzles',
      'Podcasts',
      'Collecting (vinyl / cards / sneakers)',
      'Journaling',
      'Astrology & tarot',
    ],
  },
  {
    label: 'Music',
    items: [
      'Hip-hop / rap',
      'Pop',
      'Rock / indie',
      'Electronic / EDM',
      'Jazz',
      'Classical',
      'R&B / soul',
      'Country',
      'K-pop',
      'Metal / punk',
    ],
  },
  {
    label: 'Video Games',
    items: [
      'Valorant',
      'League of Legends',
      'Minecraft',
      'Fortnite',
      'Elden Ring / Soulslikes',
      'Super Smash Bros',
      'Counter-Strike',
      'Roguelikes',
      'Nintendo / cozy games',
      'Retro / speedrunning',
    ],
  },
  {
    label: 'Film & TV',
    items: [
      'Anime',
      'Horror',
      'Sci-fi & fantasy',
      'A24 / arthouse',
      'Korean dramas',
      'Documentaries',
      'Marvel / superhero',
      'Stand-up comedy',
      'Breaking Bad',
      'The Office',
    ],
  },
  {
    label: 'Arts',
    items: [
      'Painting & drawing',
      'Photography',
      'Film photography',
      'Music production',
      'DJing',
      'Creative writing',
      'Poetry',
      'Ceramics / pottery',
      'Knitting & sewing',
      'Woodworking',
    ],
  },
  {
    label: 'Outdoors',
    items: [
      'Hiking',
      'Rock climbing',
      'Camping',
      'Cycling',
      'Skiing / snowboarding',
      'Surfing',
      'Kayaking',
      'Backpacking',
      'Fishing',
      'Stargazing',
    ],
  },
  {
    label: 'Ideas',
    items: [
      'Coding / web dev',
      'AI / machine learning',
      'Startups / entrepreneurship',
      'Robotics',
      'Crypto / blockchain',
      'Philosophy',
      'Psychology',
      'Space / astronomy',
      'Economics',
      'History',
    ],
  },
  {
    label: 'Community',
    items: [
      'Volunteering',
      'Debate / Model UN',
      'Theater / acting',
      'Improv',
      'Dance',
      'Campus journalism',
      'Climate activism',
      'Greek life',
      'Religious groups',
      'Cultural clubs',
    ],
  },
];
